# Generated by Django 2.1.7 on 2019-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Professor')], default=1, verbose_name='User Role'),
        ),
    ]
